version: '3'
services:
  trainer:
    volumes:
      - ./models:/app/models
    build: 
      context: ml-training/.
      dockerfile: Dockerfile
    command: python3 train.py
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g

  kafka:
    image: confluentinc/cp-kafka:5.5.3
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g

  data-collection:
    build:
      context: data-collection/.
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

